[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "autosinapi"
version = "0.1"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "openpyxl"
]