version: '3.8'

services:
  db:
    image: postgres:13
    container_name: autosinapi_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: autosinapi_app
    build:
      context: ../..
      dockerfile: tools/docker/Dockerfile
    env_file:
      - ./.env
    environment:
      - DOCKER_ENV=true
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mapeia a pasta de downloads local para a pasta de downloads dentro do container
      - ./downloads:/app/downloads
      # Mapeia a pasta de backups local para a pasta de backups dentro do container
      - ../../backups:/app/backups

volumes:
  postgres_data: